FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./server/package*.json ./server/
COPY ./shared/package*.json ./shared/

RUN npm ci server

COPY ./server/ ./server/
COPY ./shared/ ./shared/

RUN npm run buildBackend

EXPOSE 3001

CMD ["node", "server/dist/app.js"]